# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: guardian.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'guardian.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eguardian.proto\x12\x08guardian\"R\n\nEventBatch\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\t\x12\x1f\n\x06\x65vents\x18\x03 \x03(\x0b\x32\x0f.guardian.Event\"\xa7\x02\n\x05\x45vent\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\x05\x12\x0f\n\x07process\x18\x03 \x01(\t\x12\x0f\n\x07syscall\x18\x04 \x01(\t\x12\x0f\n\x07\x66\x64_path\x18\x05 \x01(\t\x12\r\n\x05\x62ytes\x18\x06 \x01(\x03\x12\x12\n\nreturn_val\x18\x07 \x01(\t\x12\x0b\n\x03uid\x18\x08 \x01(\x05\x12\x11\n\tprev_hash\x18\t \x01(\t\x12\x11\n\tthis_hash\x18\n \x01(\t\x12\x10\n\x08\x61gent_id\x18\x0b \x01(\t\x12\x12\n\nmodel_name\x18\x0c \x01(\t\x12\x14\n\x0c\x63ontainer_id\x18\r \x01(\t\x12\x10\n\x08pod_name\x18\x0e \x01(\t\x12\x11\n\tnamespace\x18\x0f \x01(\t\x12\x14\n\x0cnetwork_addr\x18\x10 \x01(\t\".\n\x03\x41\x63k\x12\x10\n\x08received\x18\x01 \x01(\x08\x12\x15\n\revents_stored\x18\x02 \x01(\x05\x32G\n\x0eGuardianIngest\x12\x35\n\x0cStreamEvents\x12\x14.guardian.EventBatch\x1a\r.guardian.Ack(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guardian_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTBATCH']._serialized_start=28
  _globals['_EVENTBATCH']._serialized_end=110
  _globals['_EVENT']._serialized_start=113
  _globals['_EVENT']._serialized_end=408
  _globals['_ACK']._serialized_start=410
  _globals['_ACK']._serialized_end=456
  _globals['_GUARDIANINGEST']._serialized_start=458
  _globals['_GUARDIANINGEST']._serialized_end=529
# @@protoc_insertion_point(module_scope)
