# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import guardian_pb2 as guardian__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in guardian_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GuardianIngestStub(object):
    """GuardianIngest receives signed event batches from Guardian agents.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEvents = channel.stream_unary(
                '/guardian.GuardianIngest/StreamEvents',
                request_serializer=guardian__pb2.EventBatch.SerializeToString,
                response_deserializer=guardian__pb2.Ack.FromString,
                _registered_method=True)


class GuardianIngestServicer(object):
    """GuardianIngest receives signed event batches from Guardian agents.
    """

    def StreamEvents(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuardianIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=guardian__pb2.EventBatch.FromString,
                    response_serializer=guardian__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'guardian.GuardianIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('guardian.GuardianIngest', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GuardianIngest(object):
    """GuardianIngest receives signed event batches from Guardian agents.
    """

    @staticmethod
    def StreamEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/guardian.GuardianIngest/StreamEvents',
            guardian__pb2.EventBatch.SerializeToString,
            guardian__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
